import os
env = Environment(ENV = os.environ)


env.Append(CXXFLAGS=["-std=c++11","-g","-Wall","-O3"])
env.Append(LINKFLAGS=[])

env.Program("driver",["main.cpp","parse.cpp","driver_state.cpp","shaders.cpp"])
